### ISSUE TITLE
Assertion failed on windows 7 64 with ruby 2.3.0 32

### ISSUE THREAD

**Issue by Mazwak** [rcairo/rcairo#41]
Hi

I prototyped a program on ruby 2.3.1 on linux.

I'm trying to make it work on windows 7 64, but it fails to start.

The error is :
```
Assertion failed!

Program: C:\ruby230\bin\ruby.exe
File: cairo-surface.c, Line 545

Expression: surface->is_clear

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

I tried with 2.2.4 also.

I'm not using cairo directly, but gtk3.

**Comment by kou** [comment]
Could you show a program that reproduces the problem?

**Comment by Mazwak** [comment]
From what I gathered, it is most likely not a problem of rcairo, but (ruby/)gtk.

```ruby
require 'gtk3'

win = Gtk::Window.new
treeview = Gtk::TreeView.new
treestore = Gtk::TreeStore.new(String)
column = Gtk::TreeViewColumn.new

# Comment one of the lines and it does not hit the assert
treeview.model = treestore
treeview.append_column(column)
win << treeview
###################################################

win.show_all
win.signal_connect('destroy') do
  Gtk.main_quit
end
Gtk.main
```

**Comment by kou** [comment]
Thanks. It seems that it's a bug of cairo. You're using cairo 1.15.2.

Could you report it to [the cairo mailing list](https://lists.cairographics.org/cgi-bin/mailman/listinfo/cairo) with the following backtrace?

```text
(gdb) bt full
#0  cairo_surface_create_similar (other=other@entry=0x95fabe0, content=content@entry=CAIRO_CONTENT_COLOR_ALPHA,
    width=width@entry=151, height=height@entry=0) at cairo-surface.c:545
        surface = 0x96124c0
        status = <optimized out>
        pattern = {
          base = {
            ref_count = {
              ref_count = 0
            },
            status = CAIRO_STATUS_SUCCESS,
            user_data = {
              size = 0,
              num_elements = 0,
              element_size = 24,
              elements = 0x0
            },
            observers = {
              next = 0x62d960,
              prev = 0x62d960
            },
            type = CAIRO_PATTERN_TYPE_SOLID,
            filter = CAIRO_FILTER_GOOD,
            extend = CAIRO_EXTEND_PAD,
            has_component_alpha = 0,
            matrix = {
              xx = 1,
              yx = 0,
              xy = 0,
              yy = 1,
              x0 = 0,
              y0 = 0
            },
            opacity = 1
          },
          color = {
            red = 0,
            green = 0,
            blue = 0,
            alpha = 0,
            red_short = 0,
            green_short = 0,
            blue_short = 0,
            alpha_short = 0
          }
        }
#1  0x0000000005931e4f in gdk_window_create_similar_surface (window=window@entry=0x984c020,
    content=content@entry=CAIRO_CONTENT_COLOR_ALPHA, width=width@entry=151, height=height@entry=0) at gdkwindow.c:9786
        display = <optimized out>
        rendering_mode = <optimized out>
        surface = <optimized out>
        sx = 1
        sy = 1
        __FUNCTION__ =           "gdk_window_create_similar_surface"
#2  0x000000000664d3ca in _gtk_pixel_cache_create_surface_if_needed (canvas_rect=0x62dc50, view_rect=0x62dc40,
    window=0x984c020, cache=0x9215110) at gtkpixelcache.c:242
        rect = {
          x = 0,
          y = 0,
          width = 84138784,
          height = 0
        }
        surface_w = 151
        surface_h = 0
        content = CAIRO_CONTENT_COLOR_ALPHA
#3  _gtk_pixel_cache_draw (cache=0x9215110, cr=cr@entry=0x929a8b0, window=0x984c020,
    view_rect=view_rect@entry=0x62dc40, canvas_rect=canvas_rect@entry=0x62dc50, draw=draw@entry=0x6724b70 <draw_bin>,
    user_data=user_data@entry=0x96e1830) at gtkpixelcache.c:451
No locals.
#4  0x00000000067109ae in gtk_tree_view_draw (widget=0x96e1830, cr=0x929a8b0) at gtktreeview.c:5593
        view_rect = {
          x = 0,
          y = 25,
          width = 151,
          height = 0
        }
        canvas_rect = {
          x = 0,
          y = 0,
          width = 151,
          height = 0
        }
        tree_view = 0x96e1830
        button = <optimized out>
        context = 0x94842f0
#5  0x000000000673c7ad in gtk_widget_draw_internal (widget=widget@entry=0x96e1830, cr=cr@entry=0x929a8b0,
    clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6989
        event_window = 0x98471e0
        result = 0
        push_group = <optimized out>
        clip_to_size = 1
        cr = 0x929a8b0
        widget = 0x96e1830
#6  0x00000000065398e7 in gtk_container_propagate_draw (container=container@entry=0x94747f0, child=0x96e1830,
    cr=cr@entry=0x929a8b0) at gtkcontainer.c:3838
        allocation = <optimized out>
        w = 0x98471e0
        x = 26
        y = 60
        __FUNCTION__ =           "gtk_container_propagate_draw"
#7  0x000000000653997b in gtk_container_draw (widget=0x94747f0, cr=0x929a8b0) at gtkcontainer.c:3658
        container = 0x94747f0
        child_infos = 0x984d3c0
        i = 1
        child_info = <optimized out>
        data = {
          container = 0x94747f0,
          child_infos = 0x984d3c0,
          cr = 0x929a8b0
        }
#8  0x000000000674bcaa in gtk_window_draw (widget=0x94747f0, cr=0x929a8b0) at gtkwindow.c:10258
        priv = <optimized out>
        context = 0x9484600
        ret = 0
        allocation = <optimized out>
        window_border = {
          left = 26,
          right = 26,
          top = 23,
          bottom = 29
        }
        title_height = <optimized out>
#9  0x000000000673c7ad in gtk_widget_draw_internal (widget=0x94747f0, cr=0x929a8b0, clip_to_size=<optimized out>)
    at gtkwidget.c:6989
        event_window = 0x98471e0
        result = 0
        push_group = <optimized out>
        clip_to_size = <optimized out>
        cr = 0x929a8b0
        widget = 0x94747f0
#10 0x000000000673cc90 in gtk_widget_send_expose (widget=widget@entry=0x94747f0, event=event@entry=0x62e0f0)
    at gtkwidget.c:7527
        cr = 0x929a8b0
        x = 0
        y = 0
        do_clip = 1
        __FUNCTION__ =           "gtk_widget_send_expose"
#11 0x00000000065f8016 in gtk_main_do_event (event=0x62e0f0) at gtkmain.c:1795
        is_double_buffered = <optimized out>
        event_widget = 0x94747f0
        grab_widget = 0x94747f0
        topmost_widget = <optimized out>
        window_group = 0x961eb50
        rewritten_event = <optimized out>
        device = 0x0
        tmp_list = <optimized out>
        __FUNCTION__ =           "gtk_main_do_event"
#12 0x000000000591b9f9 in _gdk_event_emit (event=event@entry=0x62e0f0) at gdkevents.c:73
No locals.
#13 0x000000000592a678 in _gdk_window_process_updates_recurse_helper (window=0x98471e0, expose_region=<optimized out>)
    at gdkwindow.c:3587
        event = {
          type = GDK_EXPOSE,
          any = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000'
          },
          expose = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            area = {
              x = 0,
              y = 0,
              width = 203,
              height = 114
            },
            region = 0x9701e10,
            count = 0
          },
          visibility = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            state = GDK_VISIBILITY_UNOBSCURED
          },
          motion = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            axes = 0x9701e10,
            state = 0,
            is_hint = 0,
            device = 0x4e87000,
            x_root = 7.8895809404623969e-316,
            y_root = 0
          },
          button = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            axes = 0x9701e10,
            state = 0,
            button = 0,
            device = 0x4e87000,
            x_root = 7.8895809404623969e-316,
            y_root = 0
          },
          touch = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            axes = 0x9701e10,
            state = 0,
            sequence = 0x4e87000,
            emulating_pointer = 159686896,
            device = 0x0,
            x_root = 0,
            y_root = 8.6934883838886848e-315
          },
          scroll = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            state = 158342672,
            direction = GDK_SCROLL_UP,
            device = 0x0,
            x_root = 4.0682298074507589e-316,
            y_root = 7.8895809404623969e-316,
            delta_x = 0,
            delta_y = 0,
            is_stop = 0
          },
          key = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            state = 0,
            keyval = 203,
            length = 114,
            string = 0x9701e10 "\001",
            hardware_keycode = 0,
            group = 0 '\000',
            is_modifier = 0
          },
          crossing = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            subwindow = 0xcb00000000,
            time = 114,
            x = 7.8231674505908666e-316,
            y = 0,
            x_root = 4.0682298074507589e-316,
            y_root = 7.8895809404623969e-316,
            mode = GDK_CROSSING_NORMAL,
            detail = GDK_NOTIFY_ANCESTOR,
            focus = 0,
            state = 0
          },
          focus_change = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            in = 0
          },
          configure = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            x = 0,
            y = 0,
            width = 203,
            height = 114
          },
          property = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            atom = 0xcb00000000,
            time = 114,
            state = 0
          },
          selection = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            selection = 0xcb00000000,
            target = 0x72,
            property = 0x9701e10,
            time = 0,
            requestor = 0x4e87000
          },
          owner_change = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            owner = 0xcb00000000,
            reason = (GDK_OWNER_CHANGE_CLOSE | unknown: 112),
            selection = 0x9701e10,
            time = 0,
            selection_time = 0
          },
          proximity = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            time = 0,
            device = 0xcb00000000
          },
          dnd = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            context = 0xcb00000000,
            time = 114,
            x_root = 0,
            y_root = 0
          },
          window_state = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            changed_mask = (unknown: 0),
            new_window_state = (unknown: 0)
          },
          setting = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            action = GDK_SETTING_ACTION_NEW,
            name = 0xcb00000000 <error: Cannot access memory at address 0xcb00000000>
          },
          grab_broken = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            keyboard = 0,
            implicit = 0,
            grab_window = 0x72
          },
          touchpad_swipe = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            phase = 0 '\000',
            n_fingers = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            dx = 7.8231674505908666e-316,
            dy = 0,
            x_root = 4.0682298074507589e-316,
            y_root = 7.8895809404623969e-316,
            state = 0
          },
          touchpad_pinch = {
            type = GDK_EXPOSE,
            window = 0x98471e0,
            send_event = 0 '\000',
            phase = 0 '\000',
            n_fingers = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            dx = 7.8231674505908666e-316,
            dy = 0,
            angle_delta = 4.0682298074507589e-316,
            scale = 7.8895809404623969e-316,
            x_root = 0,
            y_root = 0,
            state = 1759581638
          }
        }
        child = <optimized out>
        clipped_expose_region = 0x9701e10
        children = <optimized out>
        i = <optimized out>
        n_children = <optimized out>
        l = <optimized out>
        last_link = <optimized out>
#14 0x000000000592b63c in gdk_window_process_updates_internal (window=0x98471e0) at gdkwindow.c:3733
        expose_region = 0x96608f0
        impl_class = 0x500aec0
        toplevel = <optimized out>
        display = <optimized out>
        __FUNCTION__ =           "gdk_window_process_updates_internal"
#15 0x000000000592b7f3 in gdk_window_process_updates_with_mode (window=<optimized out>, recurse_mode=<optimized out>)
    at gdkwindow.c:3934
        impl_window = 0x98471e0
        list = 0x9718d80
        node = 0x9718d80
        recurse_mode = <optimized out>
        window = <optimized out>
#16 0x0000000063a462cd in _g_closure_invoke_va (closure=closure@entry=0x965ba70, return_value=return_value@entry=0x0,
    instance=0x984a0f0, instance@entry=0x685f2760 <g_timeout_dispatch>, args=0x62e560 "",
    args@entry=0x5923918 <gdk_frame_clock_paint_idle+824> "\213C0\205\300\017\205\375\376\377\377\203c8\277H\215\025\234
\005\005", n_params=0, param_types=0x0) at gclosure.c:867
        marshal = 0x63a47ba0 <g_cclosure_marshal_VOID__VOIDv>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0x965ba50
        __FUNCTION__ =           "_g_closure_invoke_va"
#17 0x0000000063a5ec85 in g_signal_emit_valist (instance=0x685f2760 <g_timeout_dispatch>, instance@entry=0x984a0f0,
    signal_id=signal_id@entry=135, detail=1751405808, detail@entry=0,
    var_args=0x5923918 <gdk_frame_clock_paint_idle+824> "\213C0\205\300\017\205\375\376\377\377\203c8\277H\215\025\234\0
05\005", var_args@entry=0x62e560 "") at gsignal.c:3294
        return_accu = <optimized out>
        accu = {
          g_type = 0,
          data =             {[0] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            },
            [1] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            }}
        }
        accumulator = 0x0
        emission = {
          next = 0x0,
          instance = 0x984a0f0,
          ihint = {
            signal_id = 135,
            detail = 0,
            run_type = G_SIGNAL_RUN_FIRST
          },
          state = EMISSION_RUN,
          chain_type = 157661120
        }
        signal_id = 0
        instance_type = <optimized out>
        emission_return = {
          g_type = 0,
          data =             {[0] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            },
            [1] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            }}
        }
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = 0x965ba70
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ =           "g_signal_emit_valist"
#18 0x0000000063a5f84f in g_signal_emit_by_name (instance=instance@entry=0x984a0f0,
    detailed_signal=detailed_signal@entry=0x5973ec4 <__FUNCTION__.30052+244> "paint") at gsignal.c:3481
        var_args = 0x62e560 ""
        detail = 0
        signal_id = 135
        itype = 157661120
        __FUNCTION__ =           "g_signal_emit_by_name"
#19 0x0000000005923918 in gdk_frame_clock_paint_idle (data=0x984a0f0) at gdkframeclockidle.c:430
        clock = 0x984a0f0
        clock_idle = 0x984a0f0
        priv = 0x984a010
        skip_to_resume_events = 0
        timings = 0x9796000
#20 0x0000000005911767 in gdk_threads_dispatch (data=0x9718f00,
    data@entry=<error reading variable: value has been optimized out>) at gdk.c:720
        dispatch = 0x9718f00
        ret = 0
#21 0x00000000685f2773 in g_timeout_dispatch (source=0x968dc80, callback=<optimized out>, user_data=<optimized out>)
    at gmain.c:4577
        timeout_source = 0x968dc80
        again = <optimized out>
#22 0x00000000685f1c4e in g_main_dispatch (context=0x33195b0) at gmain.c:3154
        dispatch = 0x685f2760 <g_timeout_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x9718f00
        callback = 0x5911720 <gdk_threads_dispatch>
        cb_funcs = 0x686454f0 <g_source_callback_funcs>
        cb_data = 0x968ed80
        need_destroy = <optimized out>
        source = 0x968dc80
        current = 0x9621130
        i = 0
#23 g_main_context_dispatch (context=context@entry=0x33195b0) at gmain.c:3769
No locals.
#24 0x00000000685f1f68 in g_main_context_iterate (context=0x33195b0, block=block@entry=1, dispatch=dispatch@entry=1,
    self=<optimized out>) at gmain.c:3840
        max_priority = 120
        timeout = 0
        some_ready = 1
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x96e5110
#25 0x00000000685f23f3 in g_main_loop_run (loop=0x94766f0) at gmain.c:4034
        __FUNCTION__ =           "g_main_loop_run"
#26 0x00000000065f72cd in gtk_main () at gtkmain.c:1266
        loop = 0x94766f0
#27 0x000000006b7448c7 in ffi_call_win64 () at ../src/x86/win64.S:357
No locals.
#28 0x0000000009108160 in ?? ()
```

**Comment by Mazwak** [comment]
Sorry, I didn't indicate rcairo version. Yes, it is the latest 1.15.2. I don't know cairo version, as it is included in the binary gem.
From Cairo webpage, 1.15.2 is a snapshot. The stable release is 1.14.6. Would you have time to create a gem for this version ? Mainly for Windows.

Right now, only 1.14.3 is available on windows, and it does not work either.
On ruby 2.2.4 :
```
C:\Maldi-Tof PCQ>ruby test.rb
C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86-mingw32/lib/
gobject-introspection/loader.rb: line 233
   (NULL)-WARNING **:Failed to load shared library 'libgdk-3-0.dll' referenced b
y the typelib: 'libgdk-3-0.dll': La procédure spécifiée est introuvable.
C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86-mingw32/lib/
gobject-introspection/loader.rb:167:in `const_set': wrong constant name 2BUTTON_
PRESS (NameError)
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:167:in `load_enum_value'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:200:in `block in load_enum_info'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:199:in `each'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:199:in `load_enum_info'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:63:in `load_info'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:40:in `block in load'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/repository.rb:27:in `block (2 levels) in each
'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/repository.rb:26:in `times'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/repository.rb:26:in `block in each'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/repository.rb:25:in `each'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/repository.rb:25:in `each'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection/loader.rb:39:in `load'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gdk3-3.0.8-x86-mingw32/lib/gdk3
.rb:55:in `init'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gtk3-3.0.8-x86-mingw32/lib/gtk3
.rb:64:in `init'
        from C:/ruby224/lib/ruby/gems/2.2.0/gems/gtk3-3.0.8-x86-mingw32/lib/gtk3
.rb:40:in `const_missing'
        from test.rb:4:in `<main>'
```
The file is in :
C:\ruby224\lib\ruby\gems\2.2.0\gems\gdk3-3.0.8-x86-mingw32\vendor\local\bin

On ruby 2.3.0 :
```
C:\Maldi-Tof PCQ>ruby test.rb
C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': c
annot load such file -- cairo.so (LoadError)
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/cairo-1.14.3-x86-mingw32/lib/ca
iro.rb:46:in `rescue in <top (required)>'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/cairo-1.14.3-x86-mingw32/lib/ca
iro.rb:42:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/glib2-3.0.8-x86-mingw32/lib/gli
b2.rb:107:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/gtk3-3.0.8-x86-mingw32/lib/gtk3
.rb:17:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:i
n `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:i
n `rescue in require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in
 `require'
        from test.rb:2:in `<main>'
```
This one is really missing. Most likely the gem was built before 2.3.0 release. There is a folder for 2.0, 2.1 and 2.2. Copying the 2.2 so does not work :
```
C:\Maldi-Tof PCQ>ruby test.rb
C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require':
126: Le module spÚcifiÚ est introuvable.   - C:/ruby230/lib/ruby/gems/2.3.0/gems
/cairo-1.14.3-x86-mingw32/lib/cairo.so (LoadError)
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:i
n `rescue in require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/cairo-1.14.3-x86-mingw32/lib/ca
iro.rb:46:in `rescue in <top (required)>'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/cairo-1.14.3-x86-mingw32/lib/ca
iro.rb:42:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/glib2-3.0.8-x86-mingw32/lib/gli
b2.rb:107:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x86
-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/ruby230/lib/ruby/gems/2.3.0/gems/gtk3-3.0.8-x86-mingw32/lib/gtk3
.rb:17:in `<top (required)>'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:i
n `require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:i
n `rescue in require'
        from C:/ruby230/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in
 `require'
        from test.rb:1:in `<main>'
```

Everything works fine on Fedora/Archlinux. They both ship cairo 1.14.6. I tested only ruby 2.3.1 with rcairo 1.14.3 and 1.15.2.

**Comment by kou** [comment]
> Sorry, I didn't indicate rcairo version. Yes, it is the latest 1.15.2. I don't know cairo version, as it is included in the binary gem.
> From Cairo webpage, 1.15.2 is a snapshot. The stable release is 1.14.6. Would you have time to create a gem for this version ? Mainly for Windows.

Ah, sorry. My description is too less.

I know you're using rcairo 1.15.2. And it bundles cairo 1.15.2 not 1.14.6.

I tried the script you provide and get the backtrace with rcairo 1.15.2. It means that I used cairo 1.15.2 not 1.14.6.

The backtrace says `cairo_surface_create_similar()` has a problem. The `surface` for `cairo_surface_create_similar()` is `cairo_win32_display_surface_t`. (Oh... The information doesn't exist in the backtrace...)

`cairo_surface_create_similar()` for `cairo_win32_display_surface_t` should set `1` to `surface->is_clear` as assertion says but `surface->is_clear` is `0`. So it'll be a bug of `cairo_win32_display_surface_t`'s `create_similar` implementation.

**Comment by kou** [comment]
I get `surface` and `other` information and backtrace again. Please use the information to report this problem to cairo developers:

Object inspections:

```text
(gdb) p *other
$1 = {
  backend = 0x68e7c400 <cairo_win32_display_surface_backend>,
  device = 0x97a8780,
  type = CAIRO_SURFACE_TYPE_WIN32,
  content = CAIRO_CONTENT_COLOR_ALPHA,
  ref_count = {
    ref_count = 10
  },
  status = CAIRO_STATUS_SUCCESS,
  unique_id = 30,
  serial = 23,
  damage = 0x0,
  _finishing = 0,
  finished = 0,
  is_clear = 0,
  has_font_options = 1,
  owns_device = 1,
  is_vector = 0,
  user_data = {
    size = 1,
    num_elements = 1,
    element_size = 24,
    elements = 0x978c100 "XU\005"
  },
  mime_data = {
    size = 0,
    num_elements = 0,
    element_size = 24,
    elements = 0x0
  },
  device_transform = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = 0,
    y0 = 0
  },
  device_transform_inverse = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = 0,
    y0 = 0
  },
  device_transform_observers = {
    next = 0x97a4498,
    prev = 0x97990a8
---Type <return> to continue, or q <return> to quit---
  },
  x_resolution = 72,
  y_resolution = 72,
  x_fallback_resolution = 300,
  y_fallback_resolution = 300,
  snapshot_of = 0x0,
  snapshot_detach = 0xbaadf00dbaadf00d,
  snapshots = {
    next = 0x978c038,
    prev = 0x978c038
  },
  snapshot = {
    next = 0xbaadf00dbaadf00d,
    prev = 0xbaadf00dbaadf00d
  },
  font_options = {
    antialias = CAIRO_ANTIALIAS_DEFAULT,
    subpixel_order = CAIRO_SUBPIXEL_ORDER_DEFAULT,
    lcd_filter = CAIRO_LCD_FILTER_DEFAULT,
    hint_style = CAIRO_HINT_STYLE_DEFAULT,
    hint_metrics = CAIRO_HINT_METRICS_DEFAULT,
    round_glyph_positions = CAIRO_ROUND_GLYPH_POS_DEFAULT
  }
}
(gdb) p *surface
$2 = {
  backend = 0x68e7c400 <cairo_win32_display_surface_backend>,
  device = 0x97a8780,
  type = CAIRO_SURFACE_TYPE_WIN32,
  content = CAIRO_CONTENT_COLOR_ALPHA,
  ref_count = {
    ref_count = 1
  },
  status = CAIRO_STATUS_SUCCESS,
  unique_id = 109,
  serial = 0,
  damage = 0x0,
  _finishing = 0,
  finished = 0,
  is_clear = 0,
  has_font_options = 1,
  owns_device = 1,
  is_vector = 0,
  user_data = {
    size = 0,
    num_elements = 0,
    element_size = 24,
    elements = 0x0
  },
  mime_data = {
    size = 0,
    num_elements = 0,
    element_size = 24,
    elements = 0x0
  },
  device_transform = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = 0,
    y0 = 0
  },
  device_transform_inverse = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = -0,
    y0 = -0
  },
  device_transform_observers = {
    next = 0x97323e8,
    prev = 0x97323e8
---Type <return> to continue, or q <return> to quit---
  },
  x_resolution = 72,
  y_resolution = 72,
  x_fallback_resolution = 300,
  y_fallback_resolution = 300,
  snapshot_of = 0x0,
  snapshot_detach = 0xbaadf00dbaadf00d,
  snapshots = {
    next = 0x9732428,
    prev = 0x9732428
  },
  snapshot = {
    next = 0xbaadf00dbaadf00d,
    prev = 0xbaadf00dbaadf00d
  },
  font_options = {
    antialias = CAIRO_ANTIALIAS_DEFAULT,
    subpixel_order = CAIRO_SUBPIXEL_ORDER_DEFAULT,
    lcd_filter = CAIRO_LCD_FILTER_DEFAULT,
    hint_style = CAIRO_HINT_STYLE_DEFAULT,
    hint_metrics = CAIRO_HINT_METRICS_DEFAULT,
    round_glyph_positions = CAIRO_ROUND_GLYPH_POS_DEFAULT
  }
}
```

Backtrace:

```text
(gdb) bt full
#0  cairo_surface_create_similar (other=other@entry=0x978bf30, content=content@entry=CAIRO_CONTENT_COLOR_ALPHA,
    width=width@entry=151, height=height@entry=0) at cairo-surface.c:545
        surface = 0x9732320
        status = <optimized out>
        pattern = {
          base = {
            ref_count = {
              ref_count = 0
            },
            status = CAIRO_STATUS_SUCCESS,
            user_data = {
              size = 0,
              num_elements = 0,
              element_size = 24,
              elements = 0x0
            },
            observers = {
              next = 0x62d960,
              prev = 0x62d960
            },
            type = CAIRO_PATTERN_TYPE_SOLID,
            filter = CAIRO_FILTER_GOOD,
            extend = CAIRO_EXTEND_PAD,
            has_component_alpha = 0,
            matrix = {
              xx = 1,
              yx = 0,
              xy = 0,
              yy = 1,
              x0 = 0,
              y0 = 0
            },
            opacity = 1
          },
          color = {
            red = 0,
            green = 0,
            blue = 0,
            alpha = 0,
            red_short = 0,
            green_short = 0,
            blue_short = 0,
            alpha_short = 0
          }
        }
#1  0x0000000005961e4f in gdk_window_create_similar_surface (window=window@entry=0x98ee030,
    content=content@entry=CAIRO_CONTENT_COLOR_ALPHA, width=width@entry=151, height=height@entry=0) at gdkwindow.c:9786
        display = <optimized out>
        rendering_mode = <optimized out>
---Type <return> to continue, or q <return> to quit---
        surface = <optimized out>
        sx = 1
        sy = 1
        __FUNCTION__ =           "gdk_window_create_similar_surface"
#2  0x000000000667d3ca in _gtk_pixel_cache_create_surface_if_needed (canvas_rect=0x62dc50, view_rect=0x62dc40,
    window=0x98ee030, cache=0x9316360) at gtkpixelcache.c:242
        rect = {
          x = 0,
          y = 0,
          width = 82616128,
          height = 0
        }
        surface_w = 151
        surface_h = 0
        content = CAIRO_CONTENT_COLOR_ALPHA
#3  _gtk_pixel_cache_draw (cache=0x9316360, cr=cr@entry=0x9798fa0, window=0x98ee030,
    view_rect=view_rect@entry=0x62dc40, canvas_rect=canvas_rect@entry=0x62dc50, draw=draw@entry=0x6754b70 <draw_bin>,
    user_data=user_data@entry=0x97e7dc0) at gtkpixelcache.c:451
No locals.
#4  0x00000000067409ae in gtk_tree_view_draw (widget=0x97e7dc0, cr=0x9798fa0) at gtktreeview.c:5593
        view_rect = {
          x = 0,
          y = 25,
          width = 151,
          height = 0
        }
        canvas_rect = {
          x = 0,
          y = 0,
          width = 151,
          height = 0
        }
        tree_view = 0x97e7dc0
        button = <optimized out>
        context = 0x95942f0
#5  0x000000000676c7ad in gtk_widget_draw_internal (widget=widget@entry=0x97e7dc0, cr=cr@entry=0x9798fa0,
    clip_to_size=clip_to_size@entry=1) at gtkwidget.c:6989
        event_window = 0x98e91f0
        result = 0
        push_group = <optimized out>
        clip_to_size = 1
        cr = 0x9798fa0
        widget = 0x97e7dc0
#6  0x00000000065698e7 in gtk_container_propagate_draw (container=container@entry=0x95719c0, child=0x97e7dc0,
    cr=cr@entry=0x9798fa0) at gtkcontainer.c:3838
        allocation = <optimized out>
        w = 0x98e91f0
        x = 26
        y = 60
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ =           "gtk_container_propagate_draw"
#7  0x000000000656997b in gtk_container_draw (widget=0x95719c0, cr=0x9798fa0) at gtkcontainer.c:3658
        container = 0x95719c0
        child_infos = 0x98ef3c0
        i = 1
        child_info = <optimized out>
        data = {
          container = 0x95719c0,
          child_infos = 0x98ef3c0,
          cr = 0x9798fa0
        }
#8  0x000000000677bcaa in gtk_window_draw (widget=0x95719c0, cr=0x9798fa0) at gtkwindow.c:10258
        priv = <optimized out>
        context = 0x9594600
        ret = 0
        allocation = <optimized out>
        window_border = {
          left = 26,
          right = 26,
          top = 23,
          bottom = 29
        }
        title_height = <optimized out>
#9  0x000000000676c7ad in gtk_widget_draw_internal (widget=0x95719c0, cr=0x9798fa0, clip_to_size=<optimized out>)
    at gtkwidget.c:6989
        event_window = 0x98e91f0
        result = 0
        push_group = <optimized out>
        clip_to_size = <optimized out>
        cr = 0x9798fa0
        widget = 0x95719c0
#10 0x000000000676cc90 in gtk_widget_send_expose (widget=widget@entry=0x95719c0, event=event@entry=0x62e0f0)
    at gtkwidget.c:7527
        cr = 0x9798fa0
        x = 0
        y = 0
        do_clip = 1
        __FUNCTION__ =           "gtk_widget_send_expose"
#11 0x0000000006628016 in gtk_main_do_event (event=0x62e0f0) at gtkmain.c:1795
        is_double_buffered = <optimized out>
        event_widget = 0x95719c0
        grab_widget = 0x95719c0
        topmost_widget = <optimized out>
        window_group = 0x976cb50
        rewritten_event = <optimized out>
        device = 0x0
        tmp_list = <optimized out>
        __FUNCTION__ =           "gtk_main_do_event"
#12 0x000000000594b9f9 in _gdk_event_emit (event=event@entry=0x62e0f0) at gdkevents.c:73
---Type <return> to continue, or q <return> to quit---
No locals.
#13 0x000000000595a678 in _gdk_window_process_updates_recurse_helper (window=0x98e91f0, expose_region=<optimized out>)
    at gdkwindow.c:3587
        event = {
          type = GDK_EXPOSE,
          any = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000'
          },
          expose = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            area = {
              x = 0,
              y = 0,
              width = 203,
              height = 114
            },
            region = 0x9799d90,
            count = 0
          },
          visibility = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            state = GDK_VISIBILITY_UNOBSCURED
          },
          motion = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            axes = 0x9799d90,
            state = 0,
            is_hint = 0,
            device = 0x4e70000,
            x_root = 7.9223655557103554e-316,
            y_root = 0
          },
          button = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
---Type <return> to continue, or q <return> to quit---
            y = 5.6323483625902106e-322,
            axes = 0x9799d90,
            state = 0,
            button = 0,
            device = 0x4e70000,
            x_root = 7.9223655557103554e-316,
            y_root = 0
          },
          touch = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            axes = 0x9799d90,
            state = 0,
            sequence = 0x4e70000,
            emulating_pointer = 160350464,
            device = 0x0,
            x_root = 0,
            y_root = 8.6934883838886848e-315
          },
          scroll = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            state = 158965136,
            direction = GDK_SCROLL_UP,
            device = 0x0,
            x_root = 4.0635753138144177e-316,
            y_root = 7.9223655557103554e-316,
            delta_x = 0,
            delta_y = 0,
            is_stop = 0
          },
          key = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            state = 0,
            keyval = 203,
            length = 114,
            string = 0x9799d90 "\001",
            hardware_keycode = 0,
---Type <return> to continue, or q <return> to quit---
            group = 0 '\000',
            is_modifier = 0
          },
          crossing = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            subwindow = 0xcb00000000,
            time = 114,
            x = 7.8539212584081591e-316,
            y = 0,
            x_root = 4.0635753138144177e-316,
            y_root = 7.9223655557103554e-316,
            mode = GDK_CROSSING_NORMAL,
            detail = GDK_NOTIFY_ANCESTOR,
            focus = 0,
            state = 0
          },
          focus_change = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            in = 0
          },
          configure = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            x = 0,
            y = 0,
            width = 203,
            height = 114
          },
          property = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            atom = 0xcb00000000,
            time = 114,
            state = 0
          },
          selection = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            selection = 0xcb00000000,
            target = 0x72,
            property = 0x9799d90,
            time = 0,
---Type <return> to continue, or q <return> to quit---
            requestor = 0x4e70000
          },
          owner_change = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            owner = 0xcb00000000,
            reason = (GDK_OWNER_CHANGE_CLOSE | unknown: 112),
            selection = 0x9799d90,
            time = 0,
            selection_time = 0
          },
          proximity = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            time = 0,
            device = 0xcb00000000
          },
          dnd = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            context = 0xcb00000000,
            time = 114,
            x_root = 0,
            y_root = 0
          },
          window_state = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            changed_mask = (unknown: 0),
            new_window_state = (unknown: 0)
          },
          setting = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            action = GDK_SETTING_ACTION_NEW,
            name = 0xcb00000000 <error: Cannot access memory at address 0xcb00000000>
          },
          grab_broken = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            keyboard = 0,
            implicit = 0,
            grab_window = 0x72
---Type <return> to continue, or q <return> to quit---
          },
          touchpad_swipe = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            phase = 0 '\000',
            n_fingers = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            dx = 7.8539212584081591e-316,
            dy = 0,
            x_root = 4.0635753138144177e-316,
            y_root = 7.9223655557103554e-316,
            state = 0
          },
          touchpad_pinch = {
            type = GDK_EXPOSE,
            window = 0x98e91f0,
            send_event = 0 '\000',
            phase = 0 '\000',
            n_fingers = 0 '\000',
            time = 0,
            x = 4.3076514556595028e-312,
            y = 5.6323483625902106e-322,
            dx = 7.8539212584081591e-316,
            dy = 0,
            angle_delta = 4.0635753138144177e-316,
            scale = 7.9223655557103554e-316,
            x_root = 0,
            y_root = 0,
            state = 1759581638
          }
        }
        child = <optimized out>
        clipped_expose_region = 0x9799d90
        children = <optimized out>
        i = <optimized out>
        n_children = <optimized out>
        l = <optimized out>
        last_link = <optimized out>
#14 0x000000000595b63c in gdk_window_process_updates_internal (window=0x98e91f0) at gdkwindow.c:3733
        expose_region = 0x9715530
        impl_class = 0x50072f0
        toplevel = <optimized out>
        display = <optimized out>
        __FUNCTION__ =           "gdk_window_process_updates_internal"
#15 0x000000000595b7f3 in gdk_window_process_updates_with_mode (window=<optimized out>, recurse_mode=<optimized out>)
    at gdkwindow.c:3934
---Type <return> to continue, or q <return> to quit---
        impl_window = 0x98e91f0
        list = 0x981bd80
        node = 0x981bd80
        recurse_mode = <optimized out>
        window = <optimized out>
#16 0x0000000063a462cd in _g_closure_invoke_va (closure=closure@entry=0x978a360, return_value=return_value@entry=0x0,
    instance=0x98ec100, instance@entry=0x685f2760 <g_timeout_dispatch>, args=0x62e560 "",
    args@entry=0x5953918 <gdk_frame_clock_paint_idle+824> "\213C0\205\300\017\205\375\376\377\377\203c8\277H\215\025\234
\005\005", n_params=0, param_types=0x0) at gclosure.c:867
        marshal = 0x63a47ba0 <g_cclosure_marshal_VOID__VOIDv>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0x978a340
        __FUNCTION__ =           "_g_closure_invoke_va"
#17 0x0000000063a5ec85 in g_signal_emit_valist (instance=0x685f2760 <g_timeout_dispatch>, instance@entry=0x98ec100,
    signal_id=signal_id@entry=135, detail=1751405808, detail@entry=0,
    var_args=0x5953918 <gdk_frame_clock_paint_idle+824> "\213C0\205\300\017\205\375\376\377\377\203c8\277H\215\025\234\0
05\005", var_args@entry=0x62e560 "") at gsignal.c:3294
        return_accu = <optimized out>
        accu = {
          g_type = 0,
          data =             {[0] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            },
            [1] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            }}
        }
        accumulator = 0x0
        emission = {
          next = 0x0,
          instance = 0x98ec100,
          ihint = {
---Type <return> to continue, or q <return> to quit---
            signal_id = 135,
            detail = 0,
            run_type = G_SIGNAL_RUN_FIRST
          },
          state = EMISSION_RUN,
          chain_type = 158900400
        }
        signal_id = 0
        instance_type = <optimized out>
        emission_return = {
          g_type = 0,
          data =             {[0] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            },
            [1] = {
              v_int = 0,
              v_uint = 0,
              v_long = 0,
              v_ulong = 0,
              v_int64 = 0,
              v_uint64 = 0,
              v_float = 0,
              v_double = 0,
              v_pointer = 0x0
            }}
        }
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = 0x978a360
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ =           "g_signal_emit_valist"
#18 0x0000000063a5f84f in g_signal_emit_by_name (instance=instance@entry=0x98ec100,
    detailed_signal=detailed_signal@entry=0x59a3ec4 <__FUNCTION__.30052+244> "paint") at gsignal.c:3481
---Type <return> to continue, or q <return> to quit---
        var_args = 0x62e560 ""
        detail = 0
        signal_id = 135
        itype = 158900400
        __FUNCTION__ =           "g_signal_emit_by_name"
#19 0x0000000005953918 in gdk_frame_clock_paint_idle (data=0x98ec100) at gdkframeclockidle.c:430
        clock = 0x98ec100
        clock_idle = 0x98ec100
        priv = 0x98ec020
        skip_to_resume_events = 0
        timings = 0x985f000
#20 0x0000000005941767 in gdk_threads_dispatch (data=0x981bf00,
    data@entry=<error reading variable: value has been optimized out>) at gdk.c:720
        dispatch = 0x981bf00
        ret = 0
#21 0x00000000685f2773 in g_timeout_dispatch (source=0x97a5650, callback=<optimized out>, user_data=<optimized out>)
    at gmain.c:4577
        timeout_source = 0x97a5650
        again = <optimized out>
#22 0x00000000685f1c4e in g_main_dispatch (context=0x3289c70) at gmain.c:3154
        dispatch = 0x685f2760 <g_timeout_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x981bf00
        callback = 0x5941720 <gdk_threads_dispatch>
        cb_funcs = 0x686454f0 <g_source_callback_funcs>
        cb_data = 0x979cae0
        need_destroy = <optimized out>
        source = 0x97a5650
        current = 0x976f130
        i = 0
#23 g_main_context_dispatch (context=context@entry=0x3289c70) at gmain.c:3769
No locals.
#24 0x00000000685f1f68 in g_main_context_iterate (context=0x3289c70, block=block@entry=1, dispatch=dispatch@entry=1,
    self=<optimized out>) at gmain.c:3840
        max_priority = 120
        timeout = 0
        some_ready = 1
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x9811600
#25 0x00000000685f23f3 in g_main_loop_run (loop=0x92caf30) at gmain.c:4034
        __FUNCTION__ =           "g_main_loop_run"
#26 0x00000000066272cd in gtk_main () at gtkmain.c:1266
        loop = 0x92caf30
#27 0x000000006b7448c7 in ffi_call_win64 () at ../src/x86/win64.S:357
No locals.
#28 0x000000000955e480 in ?? ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by Mazwak** [comment]
Reported on main list :
https://lists.cairographics.org/archives/cairo/2016-May/027418.html

**Comment by Mazwak** [comment]
I think you missed my point between 1.14 and 1.15.
I want to emphasize that 1.15.2 is not a stable release. 1.14.6 is the latest stable.
So, I'm asking if you can provide rcairo 1.14.6, mainly for windows.

I also pointed out that ruby-gtk3 3.0.8 does not work with rcairo 1.14.3. Providing rcairo 1.14.6 would also mean to be careful about that fact. Maybe I should open another bug ? Here or in ruby-gnome2.

**Comment by Mazwak** [comment]
It's been 2 months now. Could you please provide rcairo linked against cairo 1.14.6 for windows ?

**Comment by kou** [comment]
I've released rcairo 1.14.6 that bundles cairo 1.14.6.

**Comment by Mazwak** [comment]
Many thanks

**Comment by Mazwak** [comment]
The bug is still present on the newest versions of rcairo : 1.15.4.

A bug has been opened (not by me) : https://bugs.freedesktop.org/show_bug.cgi?id=99054

I tried to put show_all before I create the treeview, and the assertion is not raised.

However, if I load a builder file, it raises the assertion before I can call show_all.

Could you please add a patch similar to the one in the bug report for the win32 build ?

**Comment by kou** [comment]
Please try cairo gem 1.15.5.

**Comment by Mazwak** [comment]
Works so far. Thanks.

However, there is no binary gem for win32 x64, if you could build it also.

**Comment by kou** [comment]
Oh, I failed to upload. I've uploaded.
